apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: foobar-policy
  namespace: api
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: api
  tls:
    minVersion: "1.2"
